### ISSUE TITLE
Import project directly to Android Studio throws error Unkown property 'marvelProductionEndPoint'

### ISSUE THREAD

**Issue by smarques84** [JoaquimLey/avenging#30]
Here is the full error:

`Error:(18, 0) Could not get unknown property 'marvelProductionEndpoint' for ProductFlavor_Decorated{name=main, dimension=null, minSdkVersion=DefaultApiVersion{mApiLevel=11, mCodename='null'}, targetSdkVersion=DefaultApiVersion{mApiLevel=24, mCodename='null'}, renderscriptTargetApi=null, renderscriptSupportModeEnabled=null, renderscriptSupportModeBlasEnabled=null, renderscriptNdkModeEnabled=null, versionCode=null, versionName=null, applicationId=null, testApplicationId=null, testInstrumentationRunner=null, testInstrumentationRunnerArguments={}, testHandleProfiling=null, testFunctionalTest=null, signingConfig=null, resConfig=null, mBuildConfigFields={}, mResValues={}, mProguardFiles=[], mConsumerProguardFiles=[], mManifestPlaceholders={}, mWearAppUnbundled=null} of type com.android.build.gradle.internal.dsl.ProductFlavor.
<a href="openFile:/Users/smarques84/AndroidStudioProjects/avenging/core/build.gradle">Open File</a>`

**Comment by JoaquimLey** [comment]
@smarques84 **Thanks** for reporting, I removed the URL from the evnt. variables and forgot to push the latest commit.
You can expect a PR in 5m fixing this 👍
